{
  "openapi": "3.0.0",
  "info": {
    "title": "Twitch API Swagger UI (Unofficial)",
    "description": "Unofficial Swagger UI (OpenAPI 3) for Twitch API.\n\nAll endpoints are generated automatically from the [twitch docs](https://dev.twitch.tv/docs/api/reference) page.\n\n__Features:__\n\n* Swagger UI for all Twitch API endpoints\n* Schemas for _Request Query Parameters_, _Request Body_, _Response Body_\n* Some additional schemas like _Clip_, _ChatBadge_, _Prediction_, _Game_, _Channel_, _Video_ etc.\n* Response codes and examples\n\n__Repository:__ [github.com/DmitryScaletta/t[...]",
    "version": "helix"
  },
  "servers": [
    {
      "url": "https://api.twitch.tv/helix",
      "description": "Helix"
    }
  ],
  "security": [],
  "tags": [
    {
      "name": "Ads"
    },
    {
      "name": "Analytics"
    },
    {
      "name": "Bits"
    },
    {
      "name": "Channels"
    },
    {
      "name": "Channel Points"
    },
    {
      "name": "Charity"
    },
    {
      "name": "Chat"
    },
    {
      "name": "Clips"
    },
    {
      "name": "Entitlements"
    },
    {
      "name": "Extensions"
    },
    {
      "name": "EventSub"
    },
    {
      "name": "Games"
    },
    {
      "name": "Goals"
    },
    {
      "name": "Hype Train"
    },
    {
      "name": "Moderation"
    },
    {
      "name": "Polls"
    },
    {
      "name": "Predictions"
    },
    {
      "name": "Raids"
    },
    {
      "name": "Schedule"
    },
    {
      "name": "Search"
    },
    {
      "name": "Music"
    },
    {
      "name": "Streams"
    },
    {
      "name": "Subscriptions"
    },
    {
      "name": "Tags"
    },
    {
      "name": "Teams"
    },
    {
      "name": "Users"
    },
    {
      "name": "Videos"
    },
    {
      "name": "Whispers"
    }
  ],
  "paths": {
    "/channels/commercial": {
      "post": {
        "tags": [
          "Ads"
        ],
        "summary": "Starts a commercial on the specified channel.",
        "description": "Starts a commercial on the specified channel.\n\n**NOTE**: Only partners and affiliates may run commercials and they must be streaming live at the time.\n\n**NOTE**: Only the broadcaster may start a commercial; the broadcaster’s editors and moderators may not start commercials on behalf of the broadcaster.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:edit:commercial** sco[...]"
      }
    },
    "/analytics/extensions": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Gets an analytics report for one or more extensions.",
        "description": "Gets an analytics report for one or more extensions. The response contains the URLs used to download the reports (CSV files). [Learn More](https://dev.twitch.tv/docs/insights)\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **analytics:read:extensions** scope."
      }
    },
    "/analytics/games": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Gets an analytics report for one or more games.",
        "description": "Gets an analytics report for one or more games. The response contains the URLs used to download the reports (CSV files). [Learn more](https://dev.twitch.tv/docs/insights)\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **analytics:read:games** scope."
      }
    },
    "/bits/leaderboard": {
      "get": {
        "tags": [
          "Bits"
        ],
        "summary": "Gets the Bits leaderboard for the authenticated broadcaster.",
        "description": "Gets the Bits leaderboard for the authenticated broadcaster.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **bits:read** scope."
      }
    },
    "/bits/cheermotes": {
      "get": {
        "tags": [
          "Bits"
        ],
        "summary": "Gets a list of Cheermotes that users can use to cheer Bits.",
        "description": "Gets a list of Cheermotes that users can use to cheer Bits in any Bits-enabled channel’s chat room. Cheermotes are animated emotes that viewers can assign Bits to.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/extensions/transactions": {
      "get": {
        "tags": [
          "Bits"
        ],
        "summary": "Gets a list of transactions for an extension.",
        "description": "Gets a list of transactions for an extension. A transaction records the exchange of a currency (for example, Bits) for a digital product.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens)."
      }
    },
    "/channels": {
      "get": {
        "tags": [
          "Channels"
        ],
        "summary": "Gets information about one or more channels.",
        "description": "Gets information about one or more channels.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      },
      "patch": {
        "tags": [
          "Channels"
        ],
        "summary": "Updates a channel’s properties.",
        "description": "Updates a channel’s properties.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:broadcast** scope.\n\n__Request Body:__\n\nAll fields are optional, but you must specify at least one field."
      }
    },
    "/channels/editors": {
      "get": {
        "tags": [
          "Channels"
        ],
        "summary": "Gets a list of users that are editors for the specified broadcaster.",
        "description": "Gets a list of users that are editors for the specified broadcaster.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:read:editors** scope."
      }
    },
    "/channel_points/custom_rewards": {
      "post": {
        "tags": [
          "Channel Points"
        ],
        "summary": "Creates a Custom Reward in the broadcaster’s channel.",
        "description": "Creates a Custom Reward in the broadcaster’s channel. The maximum number of custom rewards per channel is 50, which includes both enabled and disabled rewards.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:redemptions** scope."
      },
      "delete": {
        "tags": [
          "Channel Points"
        ],
        "summary": "Deletes a custom reward that the broadcaster created.",
        "description": "Deletes a custom reward that the broadcaster created.\n\nThe app used to create the reward is the only app that may delete it. If the reward’s redemption status is UNFULFILLED at the time the reward is deleted, its redemption status is marked as FULFILLED.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:redemptions** scope."
      },
      "get": {
        "tags": [
          "Channel Points"
        ],
        "summary": "Gets a list of custom rewards that the specified broadcaster created.",
        "description": "Gets a list of custom rewards that the specified broadcaster created.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:read:redemptions** scope.\n\n**NOTE**: A channel may offer a maximum of 50 rewards, which includes both enabled and disabled rewards."
      },
      "patch": {
        "tags": [
          "Channel Points"
        ],
        "summary": "Updates a custom reward.",
        "description": "Updates a custom reward. The app used to create the reward is the only app that may update the reward.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:redemptions** scope.\n\n__Request Body:__\n\nThe body of the request should contain only the fields you’re updating."
      }
    },
    "/channel_points/custom_rewards/redemptions": {
      "get": {
        "tags": [
          "Channel Points"
        ],
        "summary": "Gets a list of redemptions for a custom reward.",
        "description": "Gets a list of redemptions for the specified custom reward. The app used to create the reward is the only app that may get the redemptions.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:read:redemptions** scope."
      },
      "patch": {
        "tags": [
          "Channel Points"
        ],
        "summary": "Updates a redemption’s status.",
        "description": "Updates a redemption’s status. You may update a redemption only if its status is UNFULFILLED. The app used to create the reward is the only app that may update the redemption.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:redemptions** scope."
      }
    },
    "/charity/campaigns": {
      "get": {
        "tags": [
          "Charity"
        ],
        "summary": "BETA Gets information about the broadcaster’s active charity campaign.",
        "description": "[BETA](https://dev.twitch.tv/docs/product-lifecycle) Gets information about the charity campaign that a broadcaster is running. For example, the campaign’s fundraising goal and the current amount of donations.\n\nTo receive events when progress is made towards the campaign’s goal or the broadcaster changes the fundraising goal, subscribe to the [channel.charity\\_campaign.progress](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelcharity%5Fcampaignpr[...]"
      }
    },
    "/charity/donations": {
      "get": {
        "tags": [
          "Charity"
        ],
        "summary": "BETA Gets the list of donations that users have made to the broadcaster’s active charity campaign.",
        "description": "[BETA](https://dev.twitch.tv/docs/product-lifecycle) Gets the list of donations that users have made to the broadcaster’s active charity campaign.\n\nTo receive events as donations occur, subscribe to the [channel.charity\\_campaign.donate](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelcharity%5Fcampaigndonate) subscription type.\n\n__Authorization:__\n\nRequires a user access token that includes the **channel:read:charity** scope."
      }
    },
    "/chat/chatters": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "BETA Gets the list of users that are connected to the broadcaster’s chat session.",
        "description": "[BETA](https://dev.twitch.tv/docs/product-lifecycle) Gets the list of users that are connected to the broadcaster’s chat session.\n\n**NOTE**: There is a delay between when users join and leave a chat and when the list is updated accordingly.\n\nTo determine whether a user is a moderator or VIP, use the [Get Moderators](https://dev.twitch.tv/docs/api/reference#get-moderators) and [Get VIPs](https://dev.twitch.tv/docs/api/reference#get-vips) endpoints. You can check the ro[...]"
      }
    },
    "/chat/emotes": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Gets all emotes that the specified Twitch channel created.",
        "description": "Gets all emotes that the specified Twitch channel created. Broadcasters create these custom emotes for users who subscribe to or follow the channel or cheer Bits in the channel’s chat window. [Learn More](https://dev.twitch.tv/docs/irc/emotes)\n\nFor information about the custom emotes, see [subscriber emotes](https://help.twitch.tv/s/article/subscriber-emote-guide), [Bits tier emotes](https://help.twitch.tv/s/article/custom-bit-badges-guide?language=bg#slots), and [follo[...]"
      }
    },
    "/chat/emotes/global": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Gets all global emotes.",
        "description": "Gets all [global emotes](https://www.twitch.tv/creatorcamp/en/learn-the-basics/emotes/). Global emotes are Twitch-created emotes that users can use in any Twitch chat.\n\n[Learn More](https://dev.twitch.tv/docs/irc/emotes)\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens).\n\n__Request Query Parameters:__\n\nNone"
      }
    },
    "/chat/emotes/set": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Gets emotes for one or more specified emote sets.",
        "description": "Gets emotes for one or more specified emote sets.\n\nAn emote set groups emotes that have a similar context. For example, Twitch places all the subscriber emotes that a broadcaster uploads for their channel in the same emote set.\n\n[Learn More](https://dev.twitch.tv/docs/irc/emotes)\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-acce[...]"
      }
    },
    "/chat/badges": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Gets all badges that the specified broadcaster created.",
        "description": "Gets all badges that the specified broadcaster created. The list is empty if the broadcaster hasn’t created custom chat badges. For information about custom badges, see [subscriber badges](https://help.twitch.tv/s/article/subscriber-badge-guide) and [Bits badges](https://help.twitch.tv/s/article/custom-bit-badges-guide).\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.t[...]"
      }
    },
    "/chat/badges/global": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Gets the list of chat badges that Twitch created.",
        "description": "Gets the list of chat badges that Twitch created. Users can use these badges in any channel’s chat room. For information about chat badges, see [Twitch Chat Badges Guide](https://help.twitch.tv/s/article/twitch-chat-badges-guide).\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens).\n\n__Request Query Parameters:__\n\nNone"
      }
    },
    "/chat/settings": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Gets the broadcaster’s chat settings.",
        "description": "Gets the broadcaster’s chat settings.\n\nFor an overview of chat settings, see [Chat Commands for Broadcasters and Moderators](https://help.twitch.tv/s/article/chat-commands#AllMods) and [Moderator Preferences](https://help.twitch.tv/s/article/setting-up-moderation-for-your-twitch-channel#modpreferences).\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/au[...]"
      },
      "patch": {
        "tags": [
          "Chat"
        ],
        "summary": "Updates the broadcaster’s chat settings.",
        "description": "Updates the broadcaster’s chat settings.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the `moderator:manage:chat_settings` scope.\n\n__Request Body:__\n\nAll fields are optional. Specify only those fields that you want to update.\n\nTo set the `slow_mode_wait_time` or `follower_mode_duration` field to its default value, set the corresponding `slow_mode` or `follower_mode` field to **tr[...]"
      }
    },
    "/chat/announcements": {
      "post": {
        "tags": [
          "Chat"
        ],
        "summary": "Sends an announcement to the broadcaster’s chat room.",
        "description": "Sends an announcement to the broadcaster’s chat room.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderator:manage:announcements** scope."
      }
    },
    "/chat/color": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Gets the color used for the user’s name in chat.",
        "description": "Gets the color used for the user’s name in chat.\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      },
      "put": {
        "tags": [
          "Chat"
        ],
        "summary": "Updates the color used for the user’s name in chat.",
        "description": "Updates the color used for the user’s name in chat.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **user:manage:chat\\_color** scope."
      }
    },
    "/clips": {
      "post": {
        "tags": [
          "Clips"
        ],
        "summary": "Creates a clip from the broadcaster’s stream.",
        "description": "Creates a clip from the broadcaster’s stream.\n\nThis API captures up to 90 seconds of the broadcaster’s stream. The 90 seconds spans the point in the stream from when you called the API. For example, if you call the API at the 4:00 minute mark, the API captures from approximately the 3:35 mark to approximately the 4:05 minute mark. Twitch tries its best to capture 90 seconds of the stream, but the actual length may be less. This may occur if you begin capturing the clip [...]"
      },
      "get": {
        "tags": [
          "Clips"
        ],
        "summary": "Gets one or more video clips.",
        "description": "Gets one or more video clips that were captured from streams. For information about clips, see [How to use clips](https://help.twitch.tv/s/article/how-to-use-clips).\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens).\n\n__Request Query Parameters:__\n\nThe _id_, _game\\_id_, and _broadcaster\\_id_ query parameters are mut[...]"
      }
    },
    "/entitlements/codes": {
      "get": {
        "tags": [
          "Entitlements"
        ],
        "summary": "Gets the status of one or more redemption codes for a Bits reward.",
        "description": "Gets the status of one or more redemption codes for a Bits reward. Only client IDs approved by Twitch may request a redemption code’s status.\n\nRate limit: You may send at most one request per second per user.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens). The client ID in the access token must match a client ID that Twitch has approved to provide entitlements."
      },
      "post": {
        "tags": [
          "Entitlements"
        ],
        "summary": "Redeems one or more redemption codes.",
        "description": "Redeems one or more redemption codes. Redeeming a code credits the user’s account with the entitlement; for example, a Bits reward earned by playing a game.\n\nRate limit: You may send at most one request per second per user.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens). Only client IDs approved by Twitch may redeem codes on behalf of any Twitch user account."
      }
    },
    "/entitlements/drops": {
      "get": {
        "tags": [
          "Entitlements"
        ],
        "summary": "Gets an organization’s list of entitlements that have been granted to a game, a user, or both.",
        "description": "Gets an organization’s list of entitlements that have been granted to a game, a user, or both.\n\nThe following table identifies the request parameters that you may specify based on the type of access token used.\n\n| Access token type | Parameter | Description |\n| - | - | - |\n| App | None | If you don’t specify request parameters, the request returns all entitlements that your organization owns. |\n| App | user_id | The request returns all entitlements for any game tha[...]"
      },
      "patch": {
        "tags": [
          "Entitlements"
        ],
        "summary": "Updates the Drop entitlement’s fulfillment status.",
        "description": "Updates the Drop entitlement’s fulfillment status.\n\nThe following table identifies which entitlements are updated based on the type of access token used.\n\n| Access token type | Data that’s updated |\n| - | - |\n| App | Updates all entitlements with benefits owned by the organization in the access token. |\n| User | Updates all entitlements owned by the user in the access token and where the benefits are owned by the organization in the access token. |\n\n\n__Authentic[...]"
      }
    },
    "/extensions/configurations": {
      "get": {
        "tags": [
          "Extensions"
        ],
        "summary": "Gets the specified configuration segment from the specified extension.",
        "description": "Gets the specified configuration segment from the specified extension.\n\n**Rate Limits**: You may retrieve each segment a maximum of 20 times per minute.\n\n__Authorization:__\n\nRequires a signed JSON Web Token (JWT) created by an Extension Backend Service (EBS). For signing requirements, see [Signing the JWT](https://dev.twitch.tv/docs/extensions/building/#signing-the-jwt). The signed JWT must include the `role`, `user_id`, and `exp` fields (see [JWT Schema](https://de[...]"
      },
      "put": {
        "tags": [
          "Extensions"
        ],
        "summary": "Updates a configuration segment.",
        "description": "Updates a configuration segment. The segment is limited to 5 KB. Extensions that are active on a channel do not receive the updated configuration.\n\n**Rate Limits**: You may update the configuration a maximum of 20 times per minute.\n\n__Authorization:__\n\nRequires a signed JSON Web Token (JWT) created by an Extension Backend Service (EBS). For signing requirements, see [Signing the JWT](https://dev.twitch.tv/docs/extensions/building/#signing-the-jwt). The signed JWT mu[...]"
      }
    },
    "/extensions/required_configuration": {
      "put": {
        "tags": [
          "Extensions"
        ],
        "summary": "Updates the extension’s required_configuration string.",
        "description": "Updates the extension’s required\\_configuration string. Use this endpoint if your extension requires the broadcaster to configure the extension before activating it (to require configuration, you must select **Custom/My Own Service** in Extension [Capabilities](https://dev.twitch.tv/docs/extensions/life-cycle/#capabilities)). For more information, see [Required Configurations](https://dev.twitch.tv/docs/extensions/building#required-configurations) and [Setting Required C[...]"
      }
    },
    "/extensions/pubsub": {
      "post": {
        "tags": [
          "Extensions"
        ],
        "summary": "Sends a message to one or more viewers.",
        "description": "Sends a message to one or more viewers. You can send messages to a specific channel or to all channels where your extension is active. This endpoint uses the same mechanism as the [send](https://dev.twitch.tv/docs/extensions/reference#send) JavaScript helper function used to send messages.\n\n**Rate Limits**: You may send a maximum of 100 messages per minute per combination of extension client ID and broadcaster ID.\n\n__Authorization:__\n\nRequires a signed JSON Web Toke[...]"
      }
    },
    "/extensions/live": {
      "get": {
        "tags": [
          "Extensions"
        ],
        "summary": "Gets a list of broadcasters that are streaming live and have installed or activated the extension.",
        "description": "Gets a list of broadcasters that are streaming live and have installed or activated the extension.\n\nIt may take a few minutes for the list to include or remove broadcasters that have recently gone live or stopped broadcasting.\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/extensions/jwt/secrets": {
      "get": {
        "tags": [
          "Extensions"
        ],
        "summary": "Gets an extension’s list of shared secrets.",
        "description": "Gets an extension’s list of shared secrets.\n\n__Authorization:__\n\nRequires a signed JSON Web Token (JWT) created by an Extension Backend Service (EBS). For signing requirements, see [Signing the JWT](https://dev.twitch.tv/docs/extensions/building/#signing-the-jwt). The signed JWT must include the `role`, `user_id`, and `exp` fields (see [JWT Schema](https://dev.twitch.tv/docs/extensions/reference/#jwt-schema)). The `role` field must be set to _external_."
      },
      "post": {
        "tags": [
          "Extensions"
        ],
        "summary": "Creates a shared secret used to sign and verify JWT tokens.",
        "description": "Creates a shared secret used to sign and verify JWT tokens. Creating a new secret removes the current secrets from service. Use this function only when you are ready to use the new secret it returns.\n\n__Authorization:__\n\nRequires a signed JSON Web Token (JWT) created by an Extension Backend Service (EBS). For signing requirements, see [Signing the JWT](https://dev.twitch.tv/docs/extensions/building/#signing-the-jwt). The signed JWT must include the `role`, `user_id`, [...]"
      }
    },
    "/extensions/chat": {
      "post": {
        "tags": [
          "Extensions"
        ],
        "summary": "Sends a message to the specified broadcaster’s chat room.",
        "description": "Sends a message to the specified broadcaster’s chat room. The extension’s name is used as the username for the message in the chat room. To send a chat message, your extension must enable **Chat Capabilities** (under your extension’s **Capabilities** tab).\n\n**Rate Limits**: You may send a maximum of 12 messages per minute per channel.\n\n__Authorization:__\n\nRequires a signed JSON Web Token (JWT) created by an Extension Backend Service (EBS). For signing requirements, [...]"
      }
    },
    "/extensions": {
      "get": {
        "tags": [
          "Extensions"
        ],
        "summary": "Gets information about an extension.",
        "description": "Gets information about an extension.\n\n__Authorization:__\n\nRequires a signed JSON Web Token (JWT) created by an Extension Backend Service (EBS). For signing requirements, see [Signing the JWT](https://dev.twitch.tv/docs/extensions/building/#signing-the-jwt). The signed JWT must include the `role` field (see [JWT Schema](https://dev.twitch.tv/docs/extensions/reference/#jwt-schema)), and the `role` field must be set to _external_."
      }
    },
    "/extensions/released": {
      "get": {
        "tags": [
          "Extensions"
        ],
        "summary": "Gets information about a released extension.",
        "description": "Gets information about a released extension. Returns extensions whose `state` is Released.\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/bits/extensions": {
      "get": {
        "tags": [
          "Extensions"
        ],
        "summary": "Gets the list of Bits products that belongs to the extension.",
        "description": "Gets the list of Bits products that belongs to the extension. The client ID in the app access token identifies the extension.\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens). The client ID in the app access token must be the extension’s client ID."
      },
      "put": {
        "tags": [
          "Extensions"
        ],
        "summary": "Adds or updates a Bits product that the extension created.",
        "description": "Adds or updates a Bits product that the extension created. If the SKU doesn’t exist, the product is added. You may update all fields except the `sku` field.\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens). The client ID in the app access token must be the extension’s client ID."
      }
    },
    "/eventsub/subscriptions": {
      "post": {
        "tags": [
          "EventSub"
        ],
        "summary": "Creates an EventSub subscription.",
        "description": "Creates an EventSub subscription.\n\n__Authentication:__\n\nIf you use [webhooks to receive events](https://dev.twitch.tv/docs/eventsub/handling-webhook-events), the request must specify an app access token. The request will fail if you use a user access token. If the subscription type requires user authorization, the user must have granted your app (client ID) permissions to receive those events before you subscribe to them. For example, to subscribe to [channel.subscrib[...]"
      },
      "delete": {
        "tags": [
          "EventSub"
        ],
        "summary": "Deletes an EventSub subscription.",
        "description": "Deletes an EventSub subscription.\n\n__Authentication:__\n\nIf you use [webhooks to receive events](https://dev.twitch.tv/docs/eventsub/handling-webhook-events), the request must specify an app access token. The request will fail if you use a user access token.\n\nIf you use [WebSockets to receive events](https://dev.twitch.tv/docs/eventsub/handling-websocket-events), the request must specify a user access token. The request will fail if you use an app access token. The t[...]"
      },
      "get": {
        "tags": [
          "EventSub"
        ],
        "summary": "Gets a list of EventSub subscriptions that the client in the access token created.",
        "description": "Gets a list of EventSub subscriptions that the client in the access token created.\n\n__Authentication:__\n\nIf you use [webhooks to receive events](https://dev.twitch.tv/docs/eventsub/handling-webhook-events), the request must specify an app access token. The request will fail if you use a user access token.\n\nIf you use [WebSockets to receive events](https://dev.twitch.tv/docs/eventsub/handling-websocket-events), the request must specify a user access token. The reques[...]"
      }
    },
    "/games/top": {
      "get": {
        "tags": [
          "Games"
        ],
        "summary": "Gets information about all broadcasts on Twitch.",
        "description": "Gets information about all broadcasts on Twitch.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/games": {
      "get": {
        "tags": [
          "Games"
        ],
        "summary": "Gets information about specified games.",
        "description": "Gets information about specified categories or games.\n\nYou may get up to 100 categories or games by specifying their ID or name. You may specify all IDs, all names, or a combination of IDs and names. If you specify a combination of IDs and names, the total number of IDs and names must not exceed 100.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/auth[...]"
      }
    },
    "/goals": {
      "get": {
        "tags": [
          "Goals"
        ],
        "summary": "Gets the broadcaster’s list of active goals.",
        "description": "Gets the broadcaster’s list of active goals. Use this endpoint to get the current progress of each goal.\n\nInstead of polling for the progress of a goal, consider [subscribing](https://dev.twitch.tv/docs/eventsub/manage-subscriptions) to receive notifications when a goal makes progress using the [channel.goal.progress](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelgoalprogress) subscription type. [Read More](https://dev.twitch.tv/docs/api/goals#r[...]"
      }
    },
    "/hypetrain/events": {
      "get": {
        "tags": [
          "Hype Train"
        ],
        "summary": "Gets information about the broadcaster’s current or most recent Hype Train event.",
        "description": "Gets information about the broadcaster’s current or most recent Hype Train event.\n\nInstead of polling for events, consider [subscribing](https://dev.twitch.tv/docs/eventsub/manage-subscriptions) to Hype Train events ([Begin](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelhype%5Ftrainbegin), [Progress](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelhype%5Ftrainprogress), [End](https://dev.twitch.tv/docs/eventsub/eventsub-su[...]"
      }
    },
    "/moderation/enforcements/status": {
      "post": {
        "tags": [
          "Moderation"
        ],
        "summary": "Checks whether AutoMod would flag the specified message for review.",
        "description": "Checks whether AutoMod would flag the specified message for review.\n\nAutoMod is a moderation tool that holds inappropriate or harassing chat messages for moderators to review. Moderators approve or deny the messages that AutoMod flags; only approved messages are released to chat. AutoMod detects misspellings and evasive language automatically. For information about AutoMod, see [How to Use AutoMod](https://help.twitch.tv/s/article/how-to-use-automod).\n\n**Rate Limits**[...]"
      }
    },
    "/moderation/automod/message": {
      "post": {
        "tags": [
          "Moderation"
        ],
        "summary": "Allow or deny the message that AutoMod flagged for review.",
        "description": "Allow or deny the message that AutoMod flagged for review. For information about AutoMod, see [How to Use AutoMod](https://help.twitch.tv/s/article/how-to-use-automod).\n\nTo get messages that AutoMod is holding for review, subscribe to the **automod-queue.<moderator\\_id>.<channel\\_id>** [topic](https://dev.twitch.tv/docs/pubsub#topics) using [PubSub](https://dev.twitch.tv/docs/pubsub). PubSub sends a notification to your app when AutoMod holds a message for review.\n\n[...]"
      }
    },
    "/moderation/automod/settings": {
      "get": {
        "tags": [
          "Moderation"
        ],
        "summary": "Gets the broadcaster’s AutoMod settings.",
        "description": "Gets the broadcaster’s AutoMod settings. The settings are used to automatically block inappropriate or harassing messages from appearing in the broadcaster’s chat room.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderator:read:automod\\_settings** scope."
      },
      "put": {
        "tags": [
          "Moderation"
        ],
        "summary": "Updates the broadcaster’s AutoMod settings.",
        "description": "Updates the broadcaster’s AutoMod settings. The settings are used to automatically block inappropriate or harassing messages from appearing in the broadcaster’s chat room.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderator:manage:automod\\_settings** scope.\n\n__Request Body:__\n\nBecause PUT is an overwrite operation, you must include all the fields that you want set after th[...]"
      }
    },
    "/moderation/banned": {
      "get": {
        "tags": [
          "Moderation"
        ],
        "summary": "Gets all users that the broadcaster banned or put in a timeout.",
        "description": "Gets all users that the broadcaster banned or put in a timeout.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderation:read** scope."
      }
    },
    "/moderation/bans": {
      "post": {
        "tags": [
          "Moderation"
        ],
        "summary": "Bans a user from participating in a broadcaster’s chat room or puts them in a timeout.",
        "description": "Bans a user from participating in the specified broadcaster’s chat room or puts them in a timeout.\n\nFor information about banning or putting users in a timeout, see [Ban a User](https://help.twitch.tv/s/article/how-to-manage-harassment-in-chat#TheBanFeature) and [Timeout a User](https://help.twitch.tv/s/article/how-to-manage-harassment-in-chat#TheTimeoutFeature).\n\nIf the user is currently in a timeout, you can call this endpoint to change the duration of the timeout o[...]"
      },
      "delete": {
        "tags": [
          "Moderation"
        ],
        "summary": "Removes the ban or timeout that was placed on the specified user.",
        "description": "Removes the ban or timeout that was placed on the specified user.\n\nTo ban a user, see [Ban user](https://dev.twitch.tv/docs/api/reference#ban-user).\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderator:manage:banned\\_users** scope."
      }
    },
    "/moderation/blocked_terms": {
      "get": {
        "tags": [
          "Moderation"
        ],
        "summary": "Gets the broadcaster’s list of non-private, blocked words or phrases.",
        "description": "Gets the broadcaster’s list of non-private, blocked words or phrases. These are the terms that the broadcaster or moderator added manually or that were denied by AutoMod.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderator:read:blocked\\_terms** scope."
      },
      "post": {
        "tags": [
          "Moderation"
        ],
        "summary": "Adds a word or phrase to the broadcaster’s list of blocked terms.",
        "description": "Adds a word or phrase to the broadcaster’s list of blocked terms. These are the terms that the broadcaster doesn’t want used in their chat room.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderator:manage:blocked\\_terms** scope."
      },
      "delete": {
        "tags": [
          "Moderation"
        ],
        "summary": "Removes the word or phrase from the broadcaster’s list of blocked terms.",
        "description": "Removes the word or phrase from the broadcaster’s list of blocked terms.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderator:manage:blocked\\_terms** scope."
      }
    },
    "/moderation/chat": {
      "delete": {
        "tags": [
          "Moderation"
        ],
        "summary": "Removes a single chat message or all chat messages from the broadcaster’s chat room.",
        "description": "Removes a single chat message or all chat messages from the broadcaster’s chat room.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderator:manage:chat\\_messages** scope."
      }
    },
    "/moderation/moderators": {
      "get": {
        "tags": [
          "Moderation"
        ],
        "summary": "Gets all users allowed to moderate the broadcaster’s chat room.",
        "description": "Gets all users allowed to moderate the broadcaster’s chat room.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **moderation:read** scope. If your app also adds and removes moderators, you can use the **channel:manage:moderators** scope instead."
      },
      "post": {
        "tags": [
          "Moderation"
        ],
        "summary": "Adds a moderator to the broadcaster’s chat room.",
        "description": "Adds a moderator to the broadcaster’s chat room.\n\n**Rate Limits**: The broadcaster may add a maximum of 10 moderators within a 10-second window.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:moderators** scope."
      },
      "delete": {
        "tags": [
          "Moderation"
        ],
        "summary": "Removes a moderator from the broadcaster’s chat room.",
        "description": "Removes a moderator from the broadcaster’s chat room.\n\n**Rate Limits**: The broadcaster may remove a maximum of 10 moderators within a 10-second window.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:moderators** scope."
      }
    },
    "/channels/vips": {
      "get": {
        "tags": [
          "Moderation"
        ],
        "summary": "Gets a list of the broadcaster’s VIPs.",
        "description": "Gets a list of the broadcaster’s VIPs.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:read:vips** scope. If your app also adds and removes VIP status, you can use the **channel:manage:vips** scope instead."
      },
      "post": {
        "tags": [
          "Moderation"
        ],
        "summary": "Adds the specified user as a VIP in the broadcaster’s channel.",
        "description": "Adds the specified user as a VIP in the broadcaster’s channel.\n\n**Rate Limits**: The broadcaster may add a maximum of 10 VIPs within a 10-second window.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:vips** scope."
      },
      "delete": {
        "tags": [
          "Moderation"
        ],
        "summary": "Removes the specified user as a VIP in the broadcaster’s channel.",
        "description": "Removes the specified user as a VIP in the broadcaster’s channel.\n\nIf the broadcaster is removing the user’s VIP status, the ID in the _broadcaster\\_id_ query parameter must match the user ID in the access token; otherwise, if the user is removing their VIP status themselves, the ID in the _user\\_id_ query parameter must match the user ID in the access token.\n\n**Rate Limits**: The broadcaster may remove a maximum of 10 VIPs within a 10-second window.\n\n__Authorizat[...]"
      }
    },
    "/polls": {
      "get": {
        "tags": [
          "Polls"
        ],
        "summary": "Gets a list of polls that the broadcaster created.",
        "description": "Gets a list of polls that the broadcaster created.\n\nPolls are available for 90 days after they’re created.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:read:polls** scope."
      },
      "post": {
        "tags": [
          "Polls"
        ],
        "summary": "Creates a poll that viewers in the broadcaster’s channel can vote on.",
        "description": "Creates a poll that viewers in the broadcaster’s channel can vote on.\n\nThe poll begins as soon as it’s created. You may run only one poll at a time.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:polls** scope."
      },
      "patch": {
        "tags": [
          "Polls"
        ],
        "summary": "End an active poll.",
        "description": "Ends an active poll. You have the option to end it or end it and archive it.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:polls** scope."
      }
    },
    "/predictions": {
      "get": {
        "tags": [
          "Predictions"
        ],
        "summary": "Gets a list of Channel Points Predictions that the broadcaster created.",
        "description": "Gets a list of Channel Points Predictions that the broadcaster created.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:read:predictions** scope."
      },
      "post": {
        "tags": [
          "Predictions"
        ],
        "summary": "Create a Channel Points Prediction.",
        "description": "Creates a Channel Points Prediction.\n\nWith a Channel Points Prediction, the broadcaster poses a question and viewers try to predict the outcome. The prediction runs as soon as it’s created. The broadcaster may run only one prediction at a time.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:predictions** scope."
      },
      "patch": {
        "tags": [
          "Predictions"
        ],
        "summary": "Locks, resolves, or cancels a Channel Points Prediction.",
        "description": "Locks, resolves, or cancels a Channel Points Prediction.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:predictions** scope."
      }
    },
    "/raids": {
      "post": {
        "tags": [
          "Raids"
        ],
        "summary": "Raid another channel by sending the broadcaster’s viewers to the targeted channel.",
        "description": "Raid another channel by sending the broadcaster’s viewers to the targeted channel.\n\nWhen you call the API from a chat bot or extension, the Twitch UX pops up a window at the top of the chat room that identifies the number of viewers in the raid. The raid occurs when the broadcaster clicks **Raid Now** or after the 90-second countdown expires.\n\nTo determine whether the raid successfully occurred, you must subscribe to the [Channel Raid](https://dev.twitch.tv/docs/event[...]"
      },
      "delete": {
        "tags": [
          "Raids"
        ],
        "summary": "Cancel a pending raid.",
        "description": "Cancel a pending raid.\n\nYou can cancel a raid at any point up until the broadcaster clicks **Raid Now** in the Twitch UX or the 90-second countdown expires.\n\n**Rate Limit**: The limit is 10 requests within a 10-minute window.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:raids** scope."
      }
    },
    "/schedule": {
      "get": {
        "tags": [
          "Schedule"
        ],
        "summary": "Gets the broadcaster’s streaming schedule.",
        "description": "Gets the broadcaster’s streaming schedule. You can get the entire schedule or specific segments of the schedule. [Learn More](https://help.twitch.tv/s/article/channel-page-setup#Schedule)\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/schedule/icalendar": {
      "get": {
        "tags": [
          "Schedule"
        ],
        "summary": "Gets the broadcaster’s streaming schedule as an iCalendar.",
        "description": "Gets the broadcaster’s streaming schedule as an [iCalendar](https://datatracker.ietf.org/doc/html/rfc5545).\n\n__Authorization:__\n\nThe Client-Id and Authorization headers are not required.\n\n__Response Body:__\n\nThe response body contains the iCalendar data (see [RFC5545](https://datatracker.ietf.org/doc/html/rfc5545)).\n\nThe Content-Type response header is set to `text/calendar`."
      }
    },
    "/schedule/settings": {
      "patch": {
        "tags": [
          "Schedule"
        ],
        "summary": "Updates the broadcaster’s schedule settings, such as scheduling a vacation.",
        "description": "Updates the broadcaster’s schedule settings, such as scheduling a vacation.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:schedule** scope."
      }
    },
    "/schedule/segment": {
      "post": {
        "tags": [
          "Schedule"
        ],
        "summary": "Adds a single or recurring broadcast to the broadcaster’s streaming schedule.",
        "description": "Adds a single or recurring broadcast to the broadcaster’s streaming schedule. For information about scheduling broadcasts, see [Stream Schedule](https://help.twitch.tv/s/article/channel-page-setup#Schedule).\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:schedule** scope."
      },
      "patch": {
        "tags": [
          "Schedule"
        ],
        "summary": "Updates a scheduled broadcast segment.",
        "description": "Updates a scheduled broadcast segment.\n\nFor recurring segments, updating a segment’s title, category, duration, and timezone, changes all segments in the recurring schedule, not just the specified segment.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:schedule** scope."
      },
      "delete": {
        "tags": [
          "Schedule"
        ],
        "summary": "Deletes a broadcast from the broadcaster’s streaming schedule.",
        "description": "Removes a broadcast segment from the broadcaster’s streaming schedule.\n\n**NOTE**: For recurring segments, removing a segment removes all segments in the recurring schedule.\n\n__Authorization:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:schedule** scope."
      }
    },
    "/search/categories": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "Gets the games or categories that match the specified query.",
        "description": "Gets the games or categories that match the specified query.\n\nTo match, the category’s name must contain all parts of the query string. For example, if the query string is 42, the response includes any category name that contains 42 in the title. If the query string is a phrase like _love computer_, the response includes any category name that contains the words love and computer anywhere in the name. The comparison is case insensitive.\n\n__Authentication:__\n\nRequire[...]"
      }
    },
    "helix/search/channels": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "Gets the channels that match the specified query and have streamed content within the past 6 months.",
        "description": "Gets the channels that match the specified query and have streamed content within the past 6 months.\n\nThe fields that the API uses for comparison depends on the value that the _live\\_only_ query parameter is set to. If _live\\_only_ is **false**, the API matches on the broadcaster’s login name. However, if _live\\_only_ is **true**, the API matches on the broadcaster’s name and category name.\n\nTo match, the beginning of the broadcaster’s name or category must match t[...]"
      }
    },
    "/soundtrack/current_track": {
      "get": {
        "tags": [
          "Music"
        ],
        "summary": "Gets the Soundtrack track that the broadcaster is playing.",
        "description": "Gets the Soundtrack track that the broadcaster is playing.\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/soundtrack/playlist": {
      "get": {
        "tags": [
          "Music"
        ],
        "summary": "Gets the Soundtrack playlist’s tracks.",
        "description": "Gets the Soundtrack playlist’s tracks.\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/soundtrack/playlists": {
      "get": {
        "tags": [
          "Music"
        ],
        "summary": "Gets a list of Soundtrack playlists.",
        "description": "Gets a list of Soundtrack playlists.\n\nThe response contains information about the playlists, such as their titles and descriptions. To get a playlist’s tracks, use [Get Soundtrack Playlist](https://dev.twitch.tv/docs/api/reference#get-soundtrack-playlist) endpoint.\n\n__Authorization:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/streams/key": {
      "get": {
        "tags": [
          "Streams"
        ],
        "summary": "Gets the channel’s stream key.",
        "description": "Gets the channel’s stream key.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:read:stream\\_key** scope."
      }
    },
    "/streams": {
      "get": {
        "tags": [
          "Streams"
        ],
        "summary": "Gets a list of all broadcasters that are streaming.",
        "description": "Gets a list of all broadcasters that are streaming. The list is in descending order by the number of viewers watching the stream. Because viewers come and go during a stream, it’s possible to find duplicate or missing streams in the list as you page through the results.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/streams/followed": {
      "get": {
        "tags": [
          "Streams"
        ],
        "summary": "Gets a list of live streams of broadcasters that the specified user follows.",
        "description": "Gets a list of live streams of broadcasters that the specified user follows.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **user:read:follows** scope."
      }
    },
    "/streams/markers": {
      "post": {
        "tags": [
          "Streams"
        ],
        "summary": "Adds a marker to a live stream.",
        "description": "Adds a marker to a live stream. A marker is an arbitrary point in a live stream that the broadcaster or editor wants to mark, so they can return to that spot later to create video highlights (see Video Producer, Highlights in the Twitch UX).\n\nYou may not add markers:\n\n* If the stream is not live\n* If the stream has not enabled video on demand (VOD)\n* If the stream is a premiere (a live, first-viewing event that combines uploaded videos with live chat)\n* If the stre[...]"
      },
      "get": {
        "tags": [
          "Streams"
        ],
        "summary": "Gets a list of markers from the user’s most recent stream or from the specified VOD/video.",
        "description": "Gets a list of markers from the user’s most recent stream or from the specified VOD/video. A marker is an arbitrary point in a live stream that the broadcaster or editor marked, so they can return to that spot later to create video highlights (see Video Producer, Highlights in the Twitch UX).\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **user:read:broadcast** scope."
      }
    },
    "/subscriptions": {
      "get": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Gets a list of users that subscribe to the specified broadcaster.",
        "description": "Gets a list of users that subscribe to the specified broadcaster.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:read:subscriptions** scope.\n\nA Twitch extensions may use an app access token if the broadcaster has granted the **channel:read:subscriptions** scope from within the Twitch Extensions manager."
      }
    },
    "/subscriptions/user": {
      "get": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Checks whether the user subscribes to the broadcaster’s channel.",
        "description": "Checks whether the user subscribes to the broadcaster’s channel.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **user:read:subscriptions** scope.\n\nA Twitch extensions may use an app access token if the broadcaster has granted the **user:read:subscriptions** scope from within the Twitch Extensions manager.\n\n__Request Query Parameters:__\n\n| Parameter | Type | Required? | Descrip[...]"
      }
    },
    "/tags/streams": {
      "get": {
        "tags": [
          "Tags"
        ],
        "summary": "Gets the list of all stream tags that Twitch defines. You can also filter the list by one or more tag IDs.",
        "description": "Gets a list of all stream tags that Twitch defines. The broadcaster may apply any of these to their channel except automatic tags.\n\nFor an online list of the possible tags, see [List of All Tags](https://www.twitch.tv/directory/all/tags).\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/streams/tags": {
      "get": {
        "tags": [
          "Tags"
        ],
        "summary": "Gets the list of stream tags that the broadcaster or Twitch added to their channel.",
        "description": "Gets the list of stream tags that the broadcaster or Twitch added to their channel.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      },
      "put": {
        "tags": [
          "Tags"
        ],
        "summary": "Applies one or more tags to the specified channel, overwriting existing tags.",
        "description": "Applies one or more tags to the specified channel, overwriting existing tags.\n\n**NOTE**: You may not specify automatic tags; the call fails if you specify automatic tags. Automatic tags are tags that Twitch applies to the channel. For a list of automatic tags, see [List of All Tags](https://www.twitch.tv/directory/all/tags). To get the list of possible tags programmatically, see [Get All Stream Tags](https://dev.twitch.tv/docs/api/reference#get-all-stream-tags).\n\n__Au[...]"
      }
    },
    "/teams/channel": {
      "get": {
        "tags": [
          "Teams"
        ],
        "summary": "Gets the list of Twitch teams that the broadcaster is a member of.",
        "description": "Gets the list of Twitch teams that the broadcaster is a member of.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/teams": {
      "get": {
        "tags": [
          "Teams"
        ],
        "summary": "Gets information about the specified Twitch team.",
        "description": "Gets information about the specified Twitch team. [Read More](https://help.twitch.tv/s/article/twitch-teams)\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Gets information about one or more users.",
        "description": "Gets information about one or more users.\n\nYou may look up users using their user ID, login name, or both but the sum total of the number of users you may look up is 100\\. For example, you may specify 50 IDs and 50 names or 100 IDs or names, but you cannot specify 100 IDs and 100 names.\n\nIf you don’t specify IDs or login names, the request returns information about the user in the access token if you specify a user access token.\n\nTo include the user’s verified emai[...]"
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Updates the user’s information.",
        "description": "Updates the specified user’s information. The user ID in the OAuth token identifies the user whose information you want to update.\n\nTo include the user’s verified email address in the response, the user access token must also include the **user:read:email** scope.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **user:edit** scope."
      }
    },
    "/users/follows": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Gets information about users that are following other users.",
        "description": "Gets information about users that are following other users. For example, you can use this endpoint to answer questions like “who is qotrok following,” “who is following qotrok,” or “is user X following user Y.”\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      }
    },
    "/users/blocks": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Gets the list of users that the broadcaster has blocked.",
        "description": "Gets the list of users that the broadcaster has blocked. [Read More](https://help.twitch.tv/s/article/how-to-manage-harassment-in-chat?language=en%5FUS#BlockWhispersandMessagesfromStrangers)\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **user:read:blocked\\_users** scope."
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Blocks the specified user from interacting with or having contact with the broadcaster.",
        "description": "Blocks the specified user from interacting with or having contact with the broadcaster. The user ID in the OAuth token identifies the broadcaster who is blocking the user.\n\nTo learn more about blocking users, see [Block Other Users on Twitch](https://help.twitch.tv/s/article/how-to-manage-harassment-in-chat?language=en%5FUS#BlockWhispersandMessagesfromStrangers).\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-acce[...]"
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Removes the user from the broadcaster’s list of blocked users.",
        "description": "Removes the user from the broadcaster’s list of blocked users. The user ID in the OAuth token identifies the broadcaster who’s removing the block.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **user:manage:blocked\\_users** scope."
      }
    },
    "/users/extensions/list": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Gets a list of all extensions (both active and inactive) that the broadcaster has installed.",
        "description": "Gets a list of all extensions (both active and inactive) that the broadcaster has installed. The user ID in the access token identifies the broadcaster.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **user:read:broadcast** or **user:edit:broadcast** scope. To include inactive extensions, you must include the **user:edit:broadcast** scope."
      }
    },
    "/users/extensions": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Gets the active extensions that the broadcaster has installed for each configuration.",
        "description": "Gets the active extensions that the broadcaster has installed for each configuration.\n\nNOTE: To include extensions that you have under development, you must specify a user access token that includes the **user:read:broadcast** or **user:edit:broadcast** scope.\n\n__Authentication:__\n\nRequires an [app access token](https://dev.twitch.tv/docs/authentication#app-access-tokens) or [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens)."
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Updates an installed extension’s information.",
        "description": "Updates an installed extension’s information. You can update the extension’s activation state, ID, and version number. The user ID in the access token identifies the broadcaster whose extensions you’re updating.\n\nNOTE: If you try to activate an extension under multiple extension types, the last write wins (and there is no guarantee of write order).\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that[...]"
      }
    },
    "/videos": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Gets information about one or more published videos.",
        "description": "Gets information about one or more published videos. You may get videos by ID, by user, or by game/category.\n\nYou may apply several filters to get a subset of the videos. The filters are applied as an AND operation to each video. For example, if _language_ is set to ‘de’ and _game\\_id_ is set to 21779, the response includes only videos that show playing League of Legends by users that stream in German. The filters apply only if you get videos by user ID or game ID.\n\n[...]"
      },
      "delete": {
        "tags": [
          "Videos"
        ],
        "summary": "Deletes one or more videos.",
        "description": "Deletes one or more videos. You may delete past broadcasts, highlights, or uploads.\n\n__Authentication:__\n\nRequires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the **channel:manage:videos** scope."
      }
    },
    "/whispers": {
      "post": {
        "tags": [
          "Whispers"
        ],
        "summary": "Sends a whisper message to the specified user.",
        "description": "Sends a whisper message to the specified user.\n\nNOTE: The user sending the whisper must have a verified phone number (see the **Phone Number** setting in your [Security and Privacy](https://www.twitch.tv/settings/security) settings).\n\nNOTE: The API may silently drop whispers that it suspects of violating Twitch policies. (The API does not indicate that it dropped the whisper; it returns a 204 status code as if it succeeded.)\n\n**Rate Limits**: You may whisper to a ma[...]"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Authorization": {
        "type": "apiKey",
        "description": "Example: Bearer <access_token>",
        "name": "Authorization",
        "in": "header"
      },
      "Client-Id": {
        "type": "apiKey",
        "name": "Client-Id",
        "in": "header"
      }
    }
  }
}