export const SCHEMA_OBJECT_TYPE = {
  body: 'body',
  params: 'params',
  response: 'response',
} as const;

export type SchemaObjectType =
  typeof SCHEMA_OBJECT_TYPE[keyof typeof SCHEMA_OBJECT_TYPE];

// prettier-ignore
export const responseBodySchemaNames: Record<string, [path: string, name: string][]> = {
  'get-extension-analytics':                [['data', 'ExtensionAnalytics']],
  'get-game-analytics':                     [['data', 'GameAnalytics']],
  'get-bits-leaderboard':                   [['data', 'BitsLeaderboard']],
  'get-cheermotes':                         [['data', 'Cheermote']],
  'get-extension-transactions':             [['data', 'ExtensionTransaction'], ['data.product_data', 'ExtensionTransactionProductData']],
  'get-channel-information':                [['data', 'ChannelInformation']],
  'get-channel-editors':                    [['data', 'ChannelEditor']],
  'create-custom-rewards':                  [['data', 'CustomReward']],
  'get-custom-reward':                      [['data', 'CustomReward']],
  'update-custom-reward':                   [['data', 'CustomReward']],
  'get-custom-reward-redemption':           [['data', 'CustomRewardRedemption']],
  'update-redemption-status':               [['data', 'CustomRewardRedemption']],
  'get-charity-campaign':                   [['data', 'CharityCampaign']],
  'get-charity-campaign-donations':         [['data', 'CharityCampaignDonation']],
  'get-chatters':                           [['data', 'Chatter']],
  'get-channel-emotes':                     [['data', 'ChannelEmote']],
  'get-global-emotes':                      [['data', 'GlobalEmote']],
  'get-emote-sets':                         [['data', 'EmoteSet']],
  'get-channel-chat-badges':                [['data', 'ChatBadge']],
  'get-global-chat-badges':                 [['data', 'ChatBadge']],
  'get-chat-settings':                      [['data', 'ChatSettings']],
  'update-chat-settings':                   [['data', 'ChatSettingsUpdated']],
  'get-user-chat-color':                    [['data', 'UserChatColor']],
  'get-clips':                              [['data', 'Clip']],
  'get-code-status':                        [['data', 'CodeStatus']],
  'get-drops-entitlements':                 [['data', 'DropsEntitlement']],
  'update-drops-entitlements':              [['data', 'DropsEntitlementUpdated']],
  'get-extension-configuration-segment':    [['data', 'ExtensionConfigurationSegment']],
  'get-extension-live-channels':            [['data', 'ExtensionLiveChannel']],
  'get-extension-secrets':                  [['data', 'ExtensionSecret']],
  'create-extension-secret':                [['data', 'ExtensionSecret']],
  'get-extensions':                         [['data', 'Extension'], ['data.views', 'ExtensionViews']],
  'get-released-extensions':                [['data', 'Extension'], ['data.views', 'ExtensionViews']],
  'get-extension-bits-products':            [['data', 'ExtensionBitsProduct']],
  'update-extension-bits-product':          [['data', 'ExtensionBitsProduct']],
  'create-eventsub-subscription':           [['data', 'EventSubSubscription']],
  'get-eventsub-subscriptions':             [['data', 'EventSubSubscription']],
  'get-top-games':                          [['data', 'Game']],
  'get-games':                              [['data', 'Game']],
  'get-creator-goals':                      [['data', 'CreatorGoal']],
  'get-hype-train-events':                  [['data', 'HypeTrainEvent'], ['data.event_data', 'HypeTrainEventData']],
  'check-automod-status':                   [['data', 'AutoModStatus']],
  'get-automod-settings':                   [['data', 'AutoModSettings']],
  'update-automod-settings':                [['data', 'AutoModSettings']],
  'get-banned-users':                       [['data', 'BannedUser']],
  'get-blocked-terms':                      [['data', 'BlockedTerm']],
  'add-blocked-term':                       [['data', 'BlockedTerm']],
  'get-moderators':                         [['data', 'UserModerator']],
  'get-vips':                               [['data', 'UserVip']],
  'get-polls':                              [['data', 'Poll']],
  'create-poll':                            [['data', 'Poll']],
  'end-poll':                               [['data', 'Poll']],
  'get-predictions':                        [['data', 'Prediction'], ['data.outcomes', 'PredictionOutcome']],
  'create-prediction':                      [['data', 'Prediction'], ['data.outcomes', 'PredictionOutcome']],
  'end-prediction':                         [['data', 'Prediction'], ['data.outcomes', 'PredictionOutcome']],
  'get-channel-stream-schedule':            [['data', 'ChannelStreamSchedule'],         ['data.segments', 'ChannelStreamScheduleSegment']],
  'create-channel-stream-schedule-segment': [['data', 'ChannelStreamScheduleSegments'], ['data.segments', 'ChannelStreamScheduleSegment']],
  'update-channel-stream-schedule-segment': [['data', 'ChannelStreamScheduleSegments'], ['data.segments', 'ChannelStreamScheduleSegment']],
  'search-categories':                      [['data', 'Category']],
  'search-channels':                        [['data', 'Channel']],
  'get-soundtrack-current-track':           [['data', 'SoundtrackCurrentTrackInfo'], ['data.track', 'SoundtrackCurrentTrack']],
  'get-soundtrack-playlist':                [['data', 'SoundtrackPlaylist']],
  'get-soundtrack-playlists':               [['data', 'SoundtrackPlaylists']],
  'get-streams':                            [['data', 'Stream']],
  'get-followed-streams':                   [['data', 'Stream']],
  'create-stream-marker':                   [['data', 'StreamMarkerCreated']],
  'get-stream-markers':                     [['data', 'StreamMarkers']],
  'get-broadcaster-subscriptions':          [['data', 'BroadcasterSubscription']],
  'check-user-subscription':                [['data', 'UserSubscription']],
  'get-all-stream-tags':                    [['data', 'StreamTag']],
  'get-stream-tags':                        [['data', 'StreamTag']],
  'get-channel-teams':                      [['data', 'ChannelTeam']],
  'get-teams':                              [['data', 'Team']],
  'get-users':                              [['data', 'User']],
  'update-user':                            [['data', 'User']],
  'get-users-follows':                      [['data', 'UsersFollow']],
  'get-user-block-list':                    [['data', 'UserBlockList']],
  'get-user-extensions':                    [['data', 'Extension']],
  'get-user-active-extensions':             [['data', 'Extensions']],
  'update-user-extensions':                 [['data', 'Extensions']],
  'get-videos':                             [['data', 'Video']],
};
